### PR TITLE
Draft of "major changes" table

### PR DESCRIPTION
**Pull request by jeromekelleher**
One of the main things we need is some summary of the major updates to msprime. Here's a first pass:
Screenshot from 2021-11-18 15-42-28

What do we think?

### CODE REVIEW

**Comment by grahamgower** [comment]
Looks great!

**Comment by hyanwong** [comment]
L Great TM. A few comments:

1. "Discrete and continuous *genomic* coordinates", maybe (because in the context it was written, people might think it's about demography/location)
2. "Recording full ARG" - might be worth mentioning recombination nodes and the ability to calculate the likelihood? E.g. "Use of recombination nodes to record the full ARG (allowing exact likelihood calculations)"
3. "More efficient for large numbers of populations" - maybe give values and/or a comparator - e.g. 20x more efficient than msprime 0.3 for large populations?
4. What's "restricted time interval" about?
5. Although they are a `tskit` things, should we mention metadata and individuals (i.e. the individuals table), as these are fairly major improvements to usability, I think?
6. Do we want to mention the ability to do multiple chromosomes using DTWF and the hack at https://tskit.dev/msprime/docs/latest/ancestry.html#multiple-chromosomes or is that too much of a hack at the moment?
7. Is the ability to recapitate a new thing too (since 0.3)? Seems like a pretty major improvement to me.

**Comment by andrewkern** [comment]
one observation here-- a lot of this information is hierarchically nested. would a figure a better choice? e.g.
autodraw 11_18_2021

**Comment by jeromekelleher** [comment]
> one observation here-- a lot of this information is hierarchically nested. would a figure a better choice? e.g.

Not sure I agree here: the interface is one "thing"; ancestry and mutation simulations (etc) are independent of that? I agree the line for demography and interface is very hazy though.

**Comment by jeromekelleher** [comment]
> "More efficient for large numbers of populations" - maybe give values and/or a comparator - e.g. 20x more efficient than msprime 0.3 for large populations?

That's a bit of a how-long-is-a-piece-of-string one @Yan - pre 1.0 performance was quadratic in the number of populations. Now it's much better. There's no one number, though and you'd need to say something like "for example, in a 1D stepping stone model with 100 populations, and one haploid sample drawn each from the ends of the habitat and no recombination, we are X times faster"

**Comment by hyanwong** [comment]
> > "More efficient for large numbers of populations" - maybe give values and/or a comparator - e.g. 20x more efficient than msprime 0.3 for large populations?
> 
> That's a bit of a how-long-is-a-piece-of-string one @yan - pre 1.0 performance was quadratic in the number of populations. Now it's much better. There's no one number, though and you'd need to say something like "for example, in a 1D stepping stone model with 100 populations, and one haploid sample drawn each from the ends of the habitat and no recombination, we are X times faster"

Right, don't worry if it's not easy to say: it just sounded a little hand-wavy, but perhaps there's no better way to put it succinctly.

**Comment by hyanwong** [comment]
Perhaps "improved scaling (no longer quadratic) in the number of populations"? Or is that worse?

**Comment by jeromekelleher** [comment]
> Do we want to mention the ability to do multiple chromosomes using DTWF and the hack at https://tskit.dev/msprime/docs/latest/ancestry.html#multiple-chromosomes or is that too much of a hack at the moment?

Too hacky I think, not worth bringing up.

**Comment by jeromekelleher** [comment]
Screenshot from 2021-11-19 11-28-19

Thanks for the input @hyanwong, this is very helpful. How does this look now?

**Comment by grahamgower** [comment]
Is it also worth mentioning that the interface now supports widespread use of population names as an alternative to using numerical ids?

**Comment by jeromekelleher** [comment]
Good point @grahamgower . How about 

> Improved interface with integrated metadata and referencing populations by name. Import from...

**Comment by grahamgower** [comment]
Yep, sounds good.

**Comment by jeromekelleher** [comment]
Updated

**Comment by hyanwong** [comment]
> Thanks for the input @hyanwong, this is very helpful. How does this look now?

Great! Nice work @jeromekelleher

**Comment by jeromekelleher** [comment]
OK, let's merge this then. Thanks for the input!

**Pull request merged**
