### PR TITLE
Update DTWF benchmarks and data.

### PR DESCRIPTION
**Pull request by jeromekelleher**
I've updated the code for plotting the DTWF data as I thought the existing log-scale for genome length wasn't very helpful. Things  are easier to interpret on a linear scale I think:

dtwf-perf

The ultimate plot will go out to 100Mb, but this is far as my desktop got without running out of memory. Which makes me wonder if I should include a memory usage plot with ARGON too, since this is an important metric.

One thing worries me though: I've written a quick evaluation script trying to compare the number of output trees between ARGON and msprime, and we're consistently seeing more trees with ARGON. The distribution will be the same, but with ARGON having ~10% more trees. There is a complication in that ARGON will output identical trees if they are adjacent, whereas tskit will always squash these together. The way we work around this to use the number of breakpoints from the simulator (like the GC script), but this doesn't work because the DTWF model doesn't maintain the list of breakpoints. So, I've run a quick hack to only return the unique trees from the ARGON output, but I'm not sure if this works.

I'm not sure there's much we can do about this, but I wanted to raise the issue in case anyone has experience with this.

@gtsambos, what was your experience with validating msprime and ARGON sims?

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
> The ultimate plot will go out to 100Mb, but this is far as my desktop got without running out of memory. Which makes me wonder if I should include a memory usage plot with ARGON too, since this is an important metric.

@jeromekelleher i agree that reporting RAM usage is important. This clearly communicates the required resources and will avoid naive surprises / disappointments for keen users.

**Comment by jeromekelleher** [comment]
So it turns out we weren't really measuring the CPU time accurately for ARGON, as it's using threads and we were just measuring the wall time. Also, it turns out to be a serious memory hog:

dtwf-perf

**Comment by jeromekelleher** [comment]
Modulo figure sizes (#105) is there anything else we need to do with this figure or can we consider it done?

**Comment by gtsambos** [comment]
> So it turns out we weren't really measuring the CPU time accurately for ARGON, as it's using threads and we were just measuring the wall time. Also, it turns out to be a serious memory hog:

Ugh, I'm so sorry @jeromekelleher, that's something I should have picked up on myself. (In my defence, there's no mention of ARGON being multi-threaded in either the [docs ](https://github.com/pierpal/ARGON)or the [paper](https://academic.oup.com/bioinformatics/article/32/19/3032/2196513?login=true)!, though I haven't dug into the supps fully.) Given these large discrepancies, I think I'll have to dig a bit deeper into them anyway, as they make this claim that doesn't square easily with your results above:

> Here, we present ARGON, an efficient simulator of the DTWF process that scales up to very large chromosomes, and hundreds of thoudsands of samples. The simulator offers substantially improved performance compared with recent DTWF simulators, e.g. GENOME (Liang et al., 2007), and is comparable or superior to current coalescent simulators in terms of speed and memory usage.

This was apparently including an early version of msprime, so unless there have been dramatic changes to speed/memory under the hood, you're doing something very different to each other

**Comment by gtsambos** [comment]
> Modulo figure sizes (#105) is there anything else we need to do with this figure or can we consider it done?

I'd be happy to call this done.

> @gtsambos, what was your experience with validating msprime and ARGON sims?

Yeah, I noticed that ARGON wasn't squashing the trees either. That's part of the reason why I did my validations only after converting the ARGON output into a tree sequence (I added [a method](https://github.com/tskit-dev/tsconvert/pull/18) into tsconvert that lets you do this). The method runs simplify on the tree sequence, so the edges are all squashed. When I did this, there was no discernable difference between distributions of tree spans
Screen Shot 2021-06-17 at 1 57 02 pm
or absolute numbers of coalescence times
Screen Shot 2021-06-17 at 1 56 50 pm
so I think the apparent difference in numbers of trees can be explained by this.

**Comment by jeromekelleher** [comment]
> Ugh, I'm so sorry @jeromekelleher, that's something I should have picked up on myself. (In my defence, there's no mention of ARGON being multi-threaded in either the docs or the paper!, though I haven't dug into the supps fully.) 

Nothing to apologise for @gtsambos, benchmarking is very tricky.  I don't think anything within the ARGON code is explicitly multithreaded, it's just Java. I think Java does a lot of its garbage collection as background threads, which was adding up to quite a lot here.

There's an argument for saying the wall-time is what we're interested in, but I think this is false. With simulations we always want to run replicates, so it's the total throughput given your CPU resources that's interesting. Therefore, the total user time is the correct metric to use here.

I don't think there's anything surprising about msprime being substantially better than ARGON for long genomes - we have good algorithms for merging and splitting ancestal segments, and storing the resulting ancestry as a tree sequence. I'm not sure what they were comparing with if they were comparing against msprime before, since we'd always expect Hudson's algorithm to be faster than a generation-by-generation approach like ARGON.

Thanks for the verifications, I think that answers things quite satisfactorily. Merging!

**Comment by grahamgower** [comment]
> I don't think anything within the ARGON code is explicitly multithreaded, it's just Java. I think Java does a lot of its garbage collection as background threads, which was adding up to quite a lot here.

Hmm, the java virtual machine makes benchmarking even more tricky, in large part because it consumes resources separately to the application. Last time I ran into this, the JVM used the parallel garbage collector by default (https://www.oracle.com/java/technologies/javase/gc-tuning-6.html), spawning 1 thread per CPU up to 8 CPUs + 5/8 per CPU afterwards.

There are a bunch of options around setting upper limits on memory use (e.g. `-Xmx`), but specifying the maximum heap space does not provide an upper limit on the amount of memory that will be used when running a java application. On a 32 core cluster node, java can spawn 23 garbage collection threads behind your back, which each have memory overhead distinct from the application. So if you do your benchmark on a big compute node, its entirely plausible that your memory use measurements are driven by garbage collection. Probably you want to set `-XX:ParallelGCThreads` to something small (like 2 or 4).

**Comment by jeromekelleher** [comment]
I don't think we should have to fiddle with JVM settings for our benchmarks, and just using the defaults should give representative results. I doubt the JVM is so awful that it's just spinning CPU in background threads for the sake of it, so it is doing meaningful garbage collection work in those threads. Thus, this is part of the overall CPU work implied by the simulation job.

Re memory use, the fact that it grows with the genome length says to me that it's driven by the application rather than GC threads. If it was a constant maybe, but given it grows to 8G I can't see this as being just overhead. Anyway, the basic argument from above holds: people will run the simulation with defaults. This is the observed memory usage with those defaults.

**Comment by gregorgorjanc** [comment]
Perhaps best to state in the manuscript that msprime is faster, but also that these comparisons of different algorithms implemented in different languages is tricky.

**Comment by jeromekelleher** [comment]
I don't think it is tricky to be honest in this case - we're measuring the performance of the *programs* not the algorithms. So, we just measure  the observed memory and CPU usage and report it. I'd bet good money that any amount of fiddling with JVM parameters wouldn't change the above plots in any meaningful way.

**Pull request merged**
