### PR TITLE
Add species annotations.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Updated the figure and the text a little bit. Here's how it looks:

ancestry-perf

@petrelharp what do you think? I changed the x-axis label I figured this detail made more sense to explain in the caption.

I didn't spend long looking for different species, but this seems about right to me?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
The plan is to quote the predictions for the quadratic for DroMel in the text (hundreds of hours). 

Also cc @gregorgorjanc

**Comment by jeromekelleher** [comment]
OK, here's how it looks now:

ancestry-perf

I've changed the sizes back because that's the size of all the other figures, and this one looks very different, with the sizes you use @petrelharp.

I have to say I find plotting rho / 4 *much* more confusing than plotting rho, and explaining in the text that it's 4 Ne L. Measuring L in Morgans is a good idea, though. I think the predictions for DroMel are wrong now, but I didn't want to spend time figuring out where I need to add 4s, in case you could be convinced to change it back.

**Comment by jeromekelleher** [comment]
OK, well let's make a separate PR for fiddling with the figure sizes.

What about plotting by rho / 4, how keen are you to keep that?

**Comment by petrelharp** [comment]
> I have to say I find plotting rho / 4 much more confusing than plotting rho, and explaining in the text that it's 4 Ne L.

With the change, the x-axis is just `Ne` for a 1M chromosome, and so it's really easy to read. Otherwise, the factors of 4 make it very confusing to figure out where on the plot you would actually be. For instance, imagine re-writing the explanatory sentence in the caption with the factor of 4 - it would be far less clear.  So yeah - I am pretty keen to keep the rho/4 axis - rho is pretty non-intuitive and far from the point of the figure, which is to give a handy reference to how fast things will be.

**Comment by petrelharp** [comment]
> OK, well let's make a separate PR for fiddling with the figure sizes.

Am I doing that or you?

**Comment by petrelharp** [comment]
Ah: I love the species labels, though.

**Comment by jeromekelleher** [comment]
OK, so merge?

**Comment by petrelharp** [comment]
figsizes: https://github.com/tskit-dev/msprime-1.0-paper/issues/105

**Comment by gregorgorjanc** [comment]
> Updated the figure and the text a little bit. Here's how it looks:
> 
> ancestry-perf
> 
> @petrelharp what do you think? I changed the x-axis label I figured this detail made more sense to explain in the caption.
> 
> I didn't spend long looking for different species, but this seems about right to me?

This looks very clear to me!!!! You picked just the right number of species there!

I see value in showing rho on x-axis since time scales with rho, but converting it to Ne is tedious, so I am with @petrelharp

**Pull request merged**
