### PR TITLE
Draft of simulation interface section

### PR DESCRIPTION
**Pull request by jeromekelleher**
This is a first draft of the simulation interface section.

@grahamgower, @molpopgen, any chance you could take a look
here and see what you think?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I got the [dependency graph](https://github.com/tskit-dev/msprime/network/dependents) working properly for msprime, which makes this a bit easier. Have gone through the Python packages. Probably a few more repos that correspond to distinct methods, but there's a blurry line then out to just papers that use msprime as opposed to downstream software that directly uses msprime.

**Comment by grahamgower** [comment]
Mostly looks good to me. I'm not sure how useful it is to provide a list of publications that have a reproducible pipeline (some part of which uses msprime) --- we're bound to miss a whole bunch, and in any event it's quite hard to evaluate reprodicibility without trying to run the pipelines.

[defiNETti](https://github.com/popgenmethods/defiNETti) is worth citing here I think, as it does use msprime as a core component and the corresponding paper has been quite influential: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7687905/

**Comment by molpopgen** [comment]
I agree with Graham that this read well.  I also agree that the reproducible pipeline issue will be tricky.  That term means very different things to different people, and two people with different definitions may not be able to reproduce one another's work.

**Comment by jeromekelleher** [comment]
OK, good point on the listing reproducible papers. How about we just use Martin et al as the example, and explain that the error in that paper was only found because the pipeline was easily reproducible? I do think a single script using an API is more reproducible than some set of scripts referencing external executables, munging a bunch of text files etc, so it'd be nice to emphasise this point. (I realise I'm preaching to the choir here, but this is still not obvious to a lot of people)

**Comment by grahamgower** [comment]
> How about we just use Martin et al as the example, and explain that the error in that paper was only found because the pipeline was easily reproducible?

That sounds very reasonable.

**Pull request merged**
