### PR TITLE
Demography update

### LINKED ISSUE #16: Feature section: ground truth for N(t) methods and where are lineages
As part of the stdpopsim work, we added some very nifty features for computing ground truth values and related functions for computing the location of lineages over time. We should add a features section (see #7 for what this means) describing this.

@petrelharp, @apragsdale, you're the main people involved here; any thoughts?

### PR DESCRIPTION
**Pull request by jeromekelleher**
First draft of the demography section - any chance of a quick look over please @apragsdale, @grahamgower?

I reduced the detail in the stuff about the numerical predictions @apragsdale, as I've changed my mind about including code snippets - it would be a very long paper if we did this for all new features. Instead we just want to give people an overview of what's available.

Closes #16

### CODE REVIEW

**Review by grahamgower — APPROVED** [review]
LGTM!

**Comment by apragsdale** [comment]
Looks good. Yeah very reasonable to avoid many pages of code snippets. Should that instead migrate to the docs if it isn’t detailed there already?

**Comment by jeromekelleher** [comment]
I think we're pretty well covered in [this section](https://tskit.dev/msprime/docs/latest/demography.html#numerical-utilities) of the docs @apragsdale - but do open an issue if there's something we missed.

**Comment by jeromekelleher** [comment]
Great, thanks both. Merging.

**Pull request merged**
