### PR TITLE
sieve fixup, closes #162

### LINKED ISSUE #162: Haldane's sieve reference
Actually, now that I think about it, I don't get the Haldane's sieve reference in the discussion. What's the connection to dominant and recessive alleles @petrelharp?

> This is unsurprising, since the majority of simulation software development is performed by students, who are themselves learning to code, often without formal training in software development. Although this “Haldane’s sieve” of software has produced many good tools and enabled decades of research, it also represents a missed opportunity to invest as a community in shared infrastructure and mentorship in good software development practice.

### PR DESCRIPTION
**Pull request by petrelharp**
I kinda think the analogy is too fun to pass up, but I'm probably going overboard. See what you think.

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
I like it @petrelharp ;)

**Comment by jeromekelleher** [comment]
It makes sense to me now - but I note we could delete the reference entirely without changing the meaning.

Anyone else like to weigh in?

(I vote we keep it, but giving folks a chance to air their opinion!)

**Comment by gregorgorjanc** [comment]
Keep the ref;) Its a good pun.

**Comment by jeromekelleher** [comment]
Nobody has objected, so merging.

**Pull request merged**
