### PR TITLE
pretty up example tree sequence diagram

### PR DESCRIPTION
**Pull request by castedo**
Addresses visual separation request for figure 2 in issue #202.

Also has many tweaks to improve spacing, alignment, and in general ... make prettier.

### CODE REVIEW

**Comment by castedo** [comment]
What I build on my computer looks like this https://castedo.com/temp/paper.pdf
It's better to see what this revised figure 2 looks like in the context of the pdf (above).

**Comment by gregorgorjanc** [comment]
@castedo @jeromekelleher I believe there is an error with the site 4 genotypes in the genotype matrix - see the attached photo where I worked out ancestral sequence and dropped mutations on the four samples 

BBE07B0D-0C2F-4B11-A332-DABFEADB6120

**Comment by castedo** [comment]
Wow, nice catch @gregorgorjanc, thanks! I'm embarrassed to admit I only focused on the esthetics of the diagram and never really read it. Now that I'm actually thinking about the meaning, I see that the last row of the 'Edges' table is a redundant repeat.

So I will update this diagram and update this PR when I do.

**Comment by jeromekelleher** [comment]
Looks great thanks @castedo!  Embarrassingly I hadn't checked the details of this either!

I like the aesthetic changes. I wonder if we could make the distinction between the data model and the derived properties a bit clearer by splitting it into two panels, (A) and (B).  We put the tables to the left (A), and the derived properties (the trees and genotypes) on the right (B). What do you think?

One personal aesthetic preference would be to make the node and site tables the same width, but this is totally up to you!

**Comment by jeromekelleher** [comment]
Ah right, makes sense @castedo - don't worry about flipping so, it was just an idle thought. I think splitting into (A) and (B) would be helpful allright though, some way of indicating the stored and data and derived information.

**Comment by castedo** [comment]
@jeromekelleher space is tight, so i've attempted a very minimal visual indication that tables are separate from matrix and tree. Is this something like what you were thinking?

Refresh https://castedo.com/temp/paper.pdf to see the update in context.

**Comment by jeromekelleher** [comment]
Screenshot from 2021-11-02 19-49-23

I like it @castedo, I think this will do the trick if we put a tiny bit of text in the caption as well.

What do others think?

**Comment by castedo** [comment]
@jeromekelleher I didn't follow what you mean by text in the caption. I can think of a number of possible insights readers might not see. One of them, and it's the one most directly related to the reviewer comment, is that it's not clear what in the diagram represents tables.

One idea is to add something like a caption to the big grey right panel:
image

Another idea is to just label each table a table:
image

Any thought on which works better? My teenage daughter thinks the first one is clearly better whereas I was thinking the 2nd pass better. :-) I thought the 2nd requires less mental processing, despite more ink and being less attractive.

**Comment by jeromekelleher** [comment]
I love the first option! Couldn't be clearer I think, and it really makes the grey background work "as a thing". Perfect IMO.

**Comment by castedo** [comment]
I think you and my daughter are right. The first one is better. I've squashed all updates (and update https://castedo.com/temp/paper.pdf). I tweaked the header/caption of "Tables" to be slightly bigger. Ready to merge I think.

**Comment by jeromekelleher** [comment]
Superb, thanks so much @castedo !

**Pull request merged**
