### PR TITLE
adds gene conversion section

### PR DESCRIPTION
**Pull request by fbaumdicker**
This adds the gene conversion section as discussed in #26 

The computing times for the performance chart are currently rerunning on my PC.
I messed up the gene conversion rate in the current file.
(I forgot that a population size of 1 actually means 2 in msprime).
The data in the csv file is thus wrong. I will discuss this in more detail in #26.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Great, thanks @fbaumdicker - merging.

**Comment by hyanwong** [comment]
I'm now getting

```
LaTeX Warning: File `figures/gene_conversion/gc_perf_log.pdf' not found on inpu
t line 414.


! Package pdftex.def Error: File `figures/gene_conversion/gc_perf_log.pdf' not 
found: using draft setting.

```

**Comment by fbaumdicker** [comment]
@hyanwong You can run the Rscript  figures/gene_conversion/plot_performance_gene_conversion.R to generate the pdf, when that data is available. I did not include the figure in the repo as it is currently not based on the final version of the data.
However, if you rename the data/simbac_wrong_gc_rate.csv into simbac.csv you can generate a file.
Sorry for the inconvenience, but it is just a warning, and for the moment you can also uncomment the line in the tex file.

**Comment by hyanwong** [comment]
Ah, thanks. If it's going to be the final way of doing things, do you perhaps want to add that line to the Makefile?

**Comment by hyanwong** [comment]
Also, the script says:

```
Error in ggplot(data = df_long, aes(x = sample_size, y = time, color = tool)) : 
  object 'df_long' not found
```

**Comment by fbaumdicker** [comment]
Ah, crap! Sorry, I'll fix that.

**Comment by jeromekelleher** [comment]
Just FYI @fbaumdicker, we'll be converting the figure to Python at some point for the sake of uniformity, so don't worry about formatting things nicely. Just do whatever is easiest for you, I'll take care of the final plotting.

**Comment by fbaumdicker** [comment]
Ok, good to know, sounds reasonable. Thanks @jeromekelleher

**Pull request merged**
