### PR TITLE
Discoal performance comparison

### PR DESCRIPTION
**Pull request by andrewkern**
Hey @jeromekelleher -- I've added a script here in the evaluation dir to benchmark runtime performance between discoal and msprime called `discoal_perf.py`. It looks like the other tools in that dir are still in progress so I wrote this as a stand alone. Hope that's not too much of a problem?

While this looks at time, msprime will also best discoal (by a lot...) in terms of RAM usage. If you are profiling for memory as well I'd suggest this same comparison I've implemented here, i.e., increasing sequence length while keeping r and u per bp constant.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good, thanks @andrewkern!

I'm not following what we're comparing here though - it looks like we're running mspms (which doesn't support sweeps), so we're not really comparing on discoal's real functionality?

To make this an interesting comparison, I think we have to run some sweeps. Ideally, in some situation where we spend a reasonable fraction of the simulation's time doing the sweeps, rather than the coalescent stuff. So maybe lots of recurrent sweeps?

**Comment by jeromekelleher** [comment]
Standalone script and CSV file is perfect, btw!

**Comment by andrewkern** [comment]
sorry for making this more confusing than necessary-- i'm measuring run time with sweeps. that mspms stuff is just boilerplate i brought in to that script. check out `_discoal_str_to_simulation()` which takes the discoal command line, scales for msprime, and then runs the msprime sweep sims.

**Comment by jeromekelleher** [comment]
Aha, awesome!

One more thing - I think we should probably just turn off mutations and set theta=0, as we're only interested in the ancestry simulations (maybe discoal is spending all its time generating mutations). I think you've already done this, but we've also turned off all possible output in the other sims, to be as fair as possible (since msprime doesn't really do any output).

**Comment by andrewkern** [comment]
yeah i've turned off all output from discoal (i alter the discoal source in the makefile in `tools/` before compiling), but i'm still adding mutations internally. i can definitely remake the figure with theta=0.

**Comment by jeromekelleher** [comment]
> i can definitely remake the figure with theta=0.

That would be good, please.

**Comment by jeromekelleher** [comment]
Actually, don't bother - I'll be running all these again on my machine so that we can compare the numbers and don't have to keep saying what computer things were run on. 

Merging; thanks @andrewkern!

(Now, about those three paragraphs for the text #8 ...)

**Comment by andrewkern** [comment]
writing is on my queue! are we doing PRs for single chunks of text? i'd like to take a complete pass through the ms too-- should i hold off on that for the time being? or go for it?

**Comment by jeromekelleher** [comment]
> writing is on my queue! are we doing PRs for single chunks of text?

For the first draft of the sweeps section anyway, it would be good to do it as a pr. I'd rather do things with small updates so that people don't need to get the giant edit .

**Pull request merged**
