### PR TITLE
Multiple merger coalescents

### PR DESCRIPTION
**Pull request by eldonb**
Section "Multiple-merger coalescents" 

still needs mention of scaling of time and recombination,  and how the processes are sampled;
the bibliography file can be added to the list of bib files -  comments very welcome (the pdf attached)
[msprimepaper.pdf](https://github.com/tskit-dev/msprime-1.0-paper/files/4663283/msprimepaper.pdf)

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Great, thanks @eldonb! This is a *bit* more detail than I had imagined, to be honest. I was thinking more along the lines of a two-three paragraph summary (as outlined in #7).

@JereKoskela, any thoughts here on how we can split the job up of defining the model (presumably done in some "in preparation" manuscript) and giving a high-level description of it?

**Comment by JereKoskela** [comment]
I see that G3 software articles have a 2500 word limit. This draft alone must be at least half of that, and we have at least seven more features + some other sections to fill, so I agree we need to cut back. The good news is that everything we need is probably in the draft already, so hopefully we can make a lot of progress by just deleting/rearranging material, instead of anything more time-consuming.

As far as I know, the only thing that isn't already published somewhere else is the effect of the truncation on the Beta-Xi-coalescent. Whilst it's a nice feature, it isn't really core to the multiple merger implementation overall. I would suggest skipping it, or just mention it in passing. The eventual in-preparation manuscript can then include a remark to the effect of "actually, this is already in msprime so you can use it right away".

I think the best we have space for, realistically, is a verbal description of the models + citations to other papers for details. Maybe a skeleton like:

- State the overall merger rate of a Lambda-coalescent for a general Lambda [Birkner and Blath, 2009, and references therein]. Point out some existing applied overviews, I guess [Tellier and Lemaire, 2014] and [Birkner, Blath, and Steinrucken; 2013]. Maybe others?
- Explain that diploidy results in a split of the one merger into up to four simultaneous mergers by assigning individuals into four groups uniformly at random [Moehle and Sagitov, 2003].
- Detail that we have implemented two specific classes of models: the Dirac-Xi-coalescent of [Birkner, Blath, and Eldon; 2013] exactly as described there, and the analogous Schweinsberg [2003] model in which individuals participating in mergers get split into four groups due to diploidy, and recombination takes place on the same time scale as coalescence [Schweinsberg 2003, Lemma 13].
- Some comparison to Hybrid-Lambda and Beta-Xi-Sim. The latter we outright obsolete, except that it can do separate chromosomes naturally, and incorporate weak selection for tiny selection coefficients.

**Comment by petrelharp** [comment]
Tangential note: I think this paper has a good chance of being highly cited, which makes it attractive to fancier journals than G3 (at least, Genetics!). So if it's better for the paper to have more explanation, I'd suggest finding the appropriate journal.  (also, word limits are flexible if you have a good reason)

**Comment by eldonb** [comment]
the tex source file is 2256 words;  it certainly can be cut down to a very brief verbal description along the lines of  what @JereKoskela  suggests, but  the question is if  that  would  be beneficial;  the models are maybe obvious to us but they are not to the future users of msprime, and  having a good description in the paper  of all  the models (not just the multiple merger coals)  being implemented in msprime, and  maybe why they are being implemented  (what sort of biological questions do we think msprime would be useful for)    is also of value, so I agree with   @petrelharp , but as you wish 
Genetics has a Resource article type which can  be a full length  research article; and PLOS Computational biology has no word limit, so there are  plenty of  good  options

**Comment by jeromekelleher** [comment]
OK, let's bring in what you have so, and think about cutting down later. Can you integrate what you have here into the main tex and bib files please @eldonb (rather than the current separate files)?

**Pull request closed without merging**
