### PR TITLE
ARG diagram fix

### LINKED ISSUE #151: Finalise ARG illustration figure
Here's what the ARG illustration figure currently looks like:

Screenshot from 2021-08-12 14-32-11

It would be good if the three panels had a common y axis, so that the nodes had the same height in each one.

Also would be nice if the (A), (B), (C) labels could be on top, for concistency with other figures.

### PR DESCRIPTION
**Pull request by gtsambos**
Closes #151 

I'll be up and at home tonight so let me know if there need to be any last minute fixes

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This looks better, thanks @gtsambos. It doesn't look to me like all the nodes are actually at the same height though, and the different font sizes look odd. Would it be better to change the coordinates of (A) to match B and C rather than scaling 0.45?

**Comment by gtsambos** [comment]
Re: the different font sizes, would it be better if I made the ARG ones smaller? I think the tree sequence plots will look too cluttered with bigger numbers

**Comment by gtsambos** [comment]
i'll send you some more mockups on Slack after dinner 🥘

**Comment by jeromekelleher** [comment]
Thanks @gtsambos - I think putting them all on the same coordinate space is the only real way to make this work (or at least avoiding rescaling). Happy to make the font sizes smaller - the main thing is to make it look like "one thing".

**Comment by gtsambos** [comment]
@jeromekelleher hopefully this one aligns properly?

**Comment by jeromekelleher** [comment]
Awesome, thanks @gtsambos!

**Pull request merged**
