### PR TITLE
Added tikz diagram in ARG section subfigure.

### LINKED ISSUE #85: ARG illustration
From #83:

> In the ARG section, we might make a diagram showing something that's in the full ARG but not the minimal tree sequence, to make the distinction clear? As part (b) of Figure 5?

This sounds like an excellent idea to me. How about something  like this? 

Screenshot from 2021-07-23 10-11-19

This would make a good two panel figure then I think, (a) illustrating an ARG and the full-arg representation in msprime, and (b) showing how the extra ARG nodes come to dominate in large simulations.

Perhaps we could also show the simplified, minimal tree sequence too?

Any thoughts @JereKoskela?

### PR DESCRIPTION
**Pull request by gtsambos**
Closes #85 

I realise this tikz code looks very complicated -- I usually code up my tikz diagrams so that coordinates are given in some generality, so things can be shifted around without changing lots of other things later on, and so copy-pasting is easier. Let me know if there's anything you'd like to be changed.

Also, I added the caption and subcaption packages to the preamble as I think they're needed for subfigures.

### CODE REVIEW

**Comment by gtsambos** [comment]
Also @jeromekelleher, would you mind if I put these pics in my thesis too? (referencing this paper, ofc)

**Comment by jeromekelleher** [comment]
This is great, thanks @gtsambos. Just in case you missed it I just merged #120 which removes the 4th panel (the plot) as it's not needed now we can describe the asymptotics better.

**Comment by gtsambos** [comment]
Ah right whoops, should be fixed in this latest push

**Comment by jeromekelleher** [comment]
> Also @jeromekelleher, would you mind if I put these pics in my thesis too? (referencing this paper, ofc)

Yes, of course. (Just FYI, once this does on Biorxiv I think it's licensed CC-BY, so you don't need to ask permission)

**Comment by jeromekelleher** [comment]
This looks really nice, thanks @gtsambos - I can see some improvements we could make, but let's merge this much and move from there.

**Pull request merged**
