### PR TITLE
oregon postal codes

### PR DESCRIPTION
**Pull request by andrewkern**
hey @jeromekelleher -- i noticed that you added postal codes for our addresses. here is the correct one swapped in.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
OK - I got this from [here](https://www.genetics.org/content/genetics/215/3/779.full.pdf) though, so you'd better argue it out with @petrelharp!

I

**Comment by andrewkern** [comment]
lol @petrelharp i think you got this wrong 😛

**Comment by jeromekelleher** [comment]
I did wonder why Google showed me some trees when I looked up the postcode, but I though, hey, it's Oregon!

**Comment by petrelharp** [comment]
lol, looks like I just put in my home zip code

**Pull request merged**
